iOS support for timers and notifications and other goodies
Teifun2/nextcloud-cookbook-flutter pull request #129
Opened 2022-04-19 06:41 UTC by j-koreth

2022-04-19 06:42 UTC, j-koreth commented
Other things include updating the gradle version and changed how timers were handled.

2022-04-19 07:33 UTC, Teifun2 requested changes
Thank you very much for this PR. This looks very promissing. I also sotted the small changes to the notification and i like them a lot!

I have one question. Do we need "Round" Icon assets for IOS? The flutter default Icon seemed to have transparent round corners, is this needed for good looks or will IOS make it round on its own?

2022-04-19 07:33 UTC, Teifun2 commented on lib/src/models/timer.dart
> +    print(tz.local);
Debugging statements

2022-04-19 07:33 UTC, Teifun2 commented on lib/src/widget/animated_time_progress_bar.dart
> +      print("Completed Animation Controller???");
Debugging Statement

2022-04-19 21:16 UTC, j-koreth commented
No I don't think Round icon assets are needed for iOS on my devices IOS rounds them out by default. 
I added a new commit with the debugging statements removed. Also do we need the timer_builder package still?

2022-04-20 20:45 UTC, Teifun2 commented
> Also do we need the timer_builder package still?

You are correct it is no longer needed!

2022-04-25 00:10 UTC, j-koreth commented
Done 
sorry for the delay

2022-04-25 21:19 UTC, Teifun2 commented
> Done sorry for the delay

No hurry :)
Thanks a lot for the addition!

2022-04-25 21:22 UTC, Teifun2 approved these changes

2022-04-25 21:22 UTC, merged